# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='url',
            field=models.CharField(db_index=True, editable=False, max_length=1024, verbose_name=b'Request url'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_agent',
            field=models.CharField(editable=False, max_length=1024, null=True),
        ),
    ]
