# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_logs', '0002_auto_20160418_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='content_length',
            field=models.IntegerField(editable=False, null=True, verbose_name='Content length'),
        ),
        migrations.AlterField(
            model_name='request',
            name='duration',
            field=models.FloatField(editable=False, verbose_name='Duration in milleseconds'),
        ),
        migrations.AlterField(
            model_name='request',
            name='hash',
            field=models.CharField(editable=False, help_text='Unique identifier of request. Should be unique accross all requests.', max_length=100, unique=True, verbose_name='Hash'),
        ),
        migrations.AlterField(
            model_name='request',
            name='max_level',
            field=models.SmallIntegerField(choices=[(50, 'CRITICAL'), (40, 'ERROR'), (30, 'WARNING'), (20, 'INFO'), (20, 'INFO'), (10, 'DEBUG'), (0, 'NOTSET')], db_index=True, default=0, editable=False, verbose_name='Max level'),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='Request start time'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status_code',
            field=models.SmallIntegerField(db_index=True, editable=False, verbose_name='Status code'),
        ),
        migrations.AlterField(
            model_name='request',
            name='url',
            field=models.CharField(db_index=True, editable=False, max_length=1024, verbose_name='Request url'),
        ),
    ]
